import "../styles/reset.css";
import "../styles/globals.css";
import Navbar from "@/components/primary/Navbar";
import Footer from "@/components/primary/Footer";
import Head from "next/head";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js" defer></script>
      </Head>
      <body className="bg-p-color">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
